
spring.datasource.url=jdbc:sqlserver://MAMALONA:1433;databaseName=GymDB;integratedSecurity=true;trustServerCertificate=true;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update  
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



mercadopago.access.token=TEST-1896916285885112-022517-3ad660ebca222e3f0d750840f712c79c-542149776
# mercadopago.access.token=APP_USR-1896916285885112-022517-9b71d31809eae86dfbd7bd3808013dde-542149776

logging.level.org.springframework.security=DEBUG

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html